#1

SELECT COUNT(film_id), name
FROM film_category
INNER JOIN category
ON category.category_id = film_category.category_id
GROUP BY name;

#2 Store ID, City and Country for each Store
SELECT store_id, city, country
FROM store
INNER JOIN address
ON store.address_id = address.address_id
INNER JOIN city
ON address.city_id = city.city_id
INNER JOIN country
ON city.country_id = country.country_id;

#3 Calculate the total revenue generated by each store in dollars.
SELECT SUM(amount), store.store_id
FROM store
INNER JOIN customer 
ON store.store_id = customer.store_id
INNER JOIN payment
ON customer.customer_id = payment.customer_id
GROUP BY store.store_id;

#4 Determine the average running time of films for each category.
SELECT AVG(length), name
FROM film
INNER JOIN film_category
ON film.film_id = film_category.category_id
INNER JOIN category
ON film_category.category_id = category.category_id
GROUP BY name






